# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decision_service/decision.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'decision_service/decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64\x65\x63ision_service/decision.proto\x12\x11xeiaso.net.xev.v1\x1a\x1egoogle/protobuf/duration.proto\"\x8d\x01\n\x0bPickRequest\x12\x18\n\x07\x63ontext\x18\x01 \x01(\tR\x07\x63ontext\x12\x1a\n\x08question\x18\x02 \x01(\tR\x08question\x12\x18\n\x07options\x18\x03 \x03(\tR\x07options\x12.\n\x05model\x18\x04 \x01(\x0e\x32\x18.xeiaso.net.xev.v1.ModelR\x05model\"\x89\x04\n\x0cPickResponse\x12@\n\x0e\x65xecution_time\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationR\rexecutionTime\x12\x43\n\x06logits\x18\x02 \x03(\x0b\x32+.xeiaso.net.xev.v1.PickResponse.LogitsEntryR\x06logits\x12\x62\n\x11log_probabilities\x18\x03 \x03(\x0b\x32\x35.xeiaso.net.xev.v1.PickResponse.LogProbabilitiesEntryR\x10logProbabilities\x12O\n\nconfidence\x18\x04 \x03(\x0b\x32/.xeiaso.net.xev.v1.PickResponse.ConfidenceEntryR\nconfidence\x1a\x39\n\x0bLogitsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x02R\x05value:\x02\x38\x01\x1a\x43\n\x15LogProbabilitiesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x02R\x05value:\x02\x38\x01\x1a=\n\x0f\x43onfidenceEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x02R\x05value:\x02\x38\x01*4\n\x05Model\x12\x15\n\x11MODEL_UNSPECIFIED\x10\x00\x12\x14\n\x10MODEL_QWEN3_600M\x10\x01\x32\\\n\x0f\x44\x65\x63isionService\x12I\n\x04Pick\x12\x1e.xeiaso.net.xev.v1.PickRequest\x1a\x1f.xeiaso.net.xev.v1.PickResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decision_service.decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PICKRESPONSE_LOGITSENTRY']._loaded_options = None
  _globals['_PICKRESPONSE_LOGITSENTRY']._serialized_options = b'8\001'
  _globals['_PICKRESPONSE_LOGPROBABILITIESENTRY']._loaded_options = None
  _globals['_PICKRESPONSE_LOGPROBABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_PICKRESPONSE_CONFIDENCEENTRY']._loaded_options = None
  _globals['_PICKRESPONSE_CONFIDENCEENTRY']._serialized_options = b'8\001'
  _globals['_MODEL']._serialized_start=754
  _globals['_MODEL']._serialized_end=806
  _globals['_PICKREQUEST']._serialized_start=87
  _globals['_PICKREQUEST']._serialized_end=228
  _globals['_PICKRESPONSE']._serialized_start=231
  _globals['_PICKRESPONSE']._serialized_end=752
  _globals['_PICKRESPONSE_LOGITSENTRY']._serialized_start=563
  _globals['_PICKRESPONSE_LOGITSENTRY']._serialized_end=620
  _globals['_PICKRESPONSE_LOGPROBABILITIESENTRY']._serialized_start=622
  _globals['_PICKRESPONSE_LOGPROBABILITIESENTRY']._serialized_end=689
  _globals['_PICKRESPONSE_CONFIDENCEENTRY']._serialized_start=691
  _globals['_PICKRESPONSE_CONFIDENCEENTRY']._serialized_end=752
  _globals['_DECISIONSERVICE']._serialized_start=808
  _globals['_DECISIONSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
